// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { optionalEnv } from "@/lib/env";

const SUPABASE_URL = optionalEnv("VITE_SUPABASE_URL");
const SUPABASE_PUBLISHABLE_KEY = optionalEnv("VITE_SUPABASE_PUBLISHABLE_KEY");

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

function missingSupabaseEnvError(): Error {
  return new Error(
    [
      "Supabase is not configured.",
      "Missing VITE_SUPABASE_URL and/or VITE_SUPABASE_PUBLISHABLE_KEY.",
      "Add them to your .env / .env.production and rebuild.",
    ].join("\n"),
  );
}

export const supabase =
  SUPABASE_URL && SUPABASE_PUBLISHABLE_KEY
    ? createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
        auth: {
          storage: localStorage,
          persistSession: true,
          autoRefreshToken: true,
        },
      })
    : (new Proxy(
        {},
        {
          get() {
            throw missingSupabaseEnvError();
          },
        },
      ) as unknown as ReturnType<typeof createClient<Database>>);